### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by hugo4715** [HawkAnticheat/Hawk#10]
Hello,

You can use NMS code in a maven project.
You can install the jar manually using the maven command line, and add them as normal dependencies afterward.

See [Guide to installing 3rd party JARs](http://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html)

**Comment by Islandscout** [comment]
Hey,

I've only used Maven a few times and this is might sound pretty silly, but I don't understand the point of using a dependency manager when the 1.7 jar has to be installed manually. Am I overlooking something? I've thought about using IPVP's paper fork for 1.7 NMS, but I don't feel like depending on a fork of a fork of a fork.

Good suggestion

**Comment by hugo4715** [comment]
You only need to manually install the 1.7 NMS because the spigot buildtool can build and install the 1.8 NMS (if you use '--rev 1.8').

I don't know if NMS really changes between paper and spigot.
