### ISSUE TITLE
Breaking web with a sword

### ISSUE THREAD

**Issue by hugo4715** [HawkAnticheat/Hawk#11]
Hello,
I found a false positive. When breaking cobwebs with a sword, it flags for 'block break speed'
Hawk version: BETA 1907
Output of /version:
![image](https://user-images.githubusercontent.com/10290315/61229984-77fbd000-a729-11e9-9c3d-d6d27f322e06.png)

**Comment by Islandscout** [comment]
Huh. That's funny. I'm going to have to take a look at that one tomorrow. Thanks.

**Comment by Islandscout** [comment]
I just released BETA 1908, it should fix this problem.
