### ISSUE TITLE
fly

### ISSUE THREAD

**Issue by h4p1x** [HawkAnticheat/Hawk#14]
https://cdn.discordapp.com/attachments/598246212063199233/606481992707473417/XD.mp4

**Comment by h4p1x** [comment]
https://cdn.discordapp.com/attachments/598246212063199233/606481992707473417/XD.mp4

**Comment by inzynierr** [comment]
XD

**Comment by xLiquidCode** [comment]
XD

**Comment by Islandscout** [comment]
LOL what is this?

**Comment by h4p1x** [comment]
@Islandscout hawk bypass

**Comment by Islandscout** [comment]
> @Islandscout hawk bypass

It is? No offense, but how on earth is this supposed to help development? All I'm given is some vague video in a foreign language with someone flying around. What must I do to reproduce this? For all I know, you could have been flying on a server without an anti-cheat and then claimed that you bypassed Hawk.

**Comment by Islandscout** [comment]
I think I can close this pointless issue now.
