### ISSUE TITLE
False Flags (fly, phase, speed, fast-fall, groundspoof, interia) Build 1909

### ISSUE THREAD

**Issue by german-code** [HawkAnticheat/Hawk#17]
hey @Islandscout 
i found some false flags in the above listed checks.
You can see the false positives in this video: https://youtu.be/Om4ocWt8BB8

I`m using the latest release on spigot Build 1909.

**Comment by Islandscout** [comment]
Most of those should be fixed by the next update. I'm rewriting a few movement checks. Thanks for reporting, though.
