### ISSUE TITLE
you cant walk on carpet

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#19]
you cant walk on carpet on 1.7.10

**Comment by Islandscout** [comment]
That's a version issue. Carpet bounding boxes have changed between 1.7 and 1.8. This will be fixed in a future update.

**Comment by coolpvpv1** [comment]
> That's a version issue. Carpet bounding boxes have changed between 1.7 and 1.8. This will be fixed in a future update.

ok

**Comment by Islandscout** [comment]
Should be fixed by the next update.
