### ISSUE TITLE
Some Weird False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#26]
if you have a enchanted golden apple then just jump in the void and keep eating gapples at like y 1000 in the void you get flagged back to 0 y idk why so heres the video of it https://streamable.com/fpt4s

**Comment by Islandscout** [comment]
Can you do this again, but this time run "/hawk unfilteredflags" before recording? I have a feeling that there might be some sort of arithmetic underflow condition happening.

**Comment by coolpvpv1** [comment]
> Can you do this again, but this time run "/hawk unfilteredflags" before recording? I have a feeling that there might be some sort of arithmetic underflow condition happening.

weird ive been trying to false it but ever sense the update it hasn't false anymore so idk if it was somehow fixed or what but i cant get it to false again
