### ISSUE TITLE
Phase False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#27]
if you use a piston to push yourself you will false phase heres a video of it https://streamable.com/ccgf1

**Comment by Islandscout** [comment]
This should be fixed by the next update.

**Comment by Islandscout** [comment]
Due to a slight problem, the next update doesn't fix this issue. I'll be sure to work on it by some succeeding update.

**Comment by coolpvpv1** [comment]
> Due to a slight problem, the next update doesn't fix this issue. I'll be sure to work on it by some succeeding update.

ok

**Comment by missionarydev** [comment]
Fixed in previous commits.
