### ISSUE TITLE
Fast-fall False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#30]
i was on strikepractice with these kb settings https://paste.ubuntu.com/p/YXFpmyvp2s/ and i was fighting the bots on there and when i was block hitting them i would false fast-fall heres a video of it https://streamable.com/tgxbt (server is 1.8.8 btw)

**Comment by missionarydev** [comment]
The link to the video doesn't work anymore. If this issue is still present please open a new issue with a working copy of the video. Thanks.
