### ISSUE TITLE
little bug 

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#32]
if you put hawk.cmd.* in permissionsex config it wont work you have to add hawk.cmd then add another permission for hawk.cmd.* so i thought thats kinda a little bug so im just reporting it

**Comment by Islandscout** [comment]
It's been a while since I've worked on the command system, but I think I might have done that on purpose. If this is true, then I don't know what I was thinking, but I'll get working on that. Sounds stupid, but no joke.

**Comment by Islandscout** [comment]
I've made a change in the plugin.yml; let's see if that changes anything in the next update.

**Comment by coolpvpv1** [comment]
> I've made a change in the plugin.yml; let's see if that changes anything in the next update.

works now xd
