### ISSUE TITLE
Multi-action False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#34]
if you just right click the ground while eating food you will false multi-action and drinking a potion at the ground while right clicking falses multi-action heres a video of it mc version is 1.8.8 https://streamable.com/50403

**Comment by Islandscout** [comment]
That's strange. Are you running on a 1.7 client? I could have sworn that Mojang fixed this on 1.8.

Either way, it is noted in code that 1.7 clients can send these false flags.

**Comment by Islandscout** [comment]
Should be fixed by the next update.
