### ISSUE TITLE
super mega groundspoof falses

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#48]
place a boat on the ground stand on it boom infinite groundspoof falses mc version 1.8.8

**Comment by MZPL** [comment]
I can confirm:
https://youtu.be/IrndqCtEI4Q
I'm using latest build and spigot 1.8.8: https://canary.discordapp.com/channels/347596353817542657/562023411937705984/732162162235146251

**Comment by Islandscout** [comment]
This has been fixed in BETA 2008.
