### ISSUE TITLE
Strafe, speed, small-hop false flag caused by projectiles

### ISSUE THREAD

**Issue by makindotcc** [HawkAnticheat/Hawk#51]
When strafe, smallhop and speed are enabled - the enemy will never be knocked by projectile.
https://www.youtube.com/watch?v=bMJZ3JAPiFo

**Comment by Islandscout** [comment]
Unfortunately I am unable to reproduce your issue. Can you show the result of `/hawk dev`? Also, try running `/hawk unfilteredflags` and then try getting it to false flag. Can I see your `checks.yml` file?
