### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by Lukas562Dev** [HawkAnticheat/Hawk#9]
Does it have a autoban feature??

**Comment by Islandscout** [comment]
Yes. The module is called PunishmentScheduler. It can be used to periodically run commands on players. It has a list that can contain suspected players and whether they are authorized for punishment. You can run "/hawk punish" to use this feature.

In the future, I suggest that you ask questions either on the Hawk discussion thread on the SpigotMC forum (https://www.spigotmc.org/threads/hawk-anticheat-mc-1-7-10-1-8-8.237506/) or the Hawk discord server (https://discord.gg/rQGb5DV).
